window.WALKS = [
  {
    "name": "Walk to mcleodganj",
    "file": "Walk_to_mcleodganj",
    "caption": "Inevitable quiet walk post an argument",
    "location": "Dharamsala, India",
    "front": "Walk_to_mcleodganj-front.webp",
    "back": "Walk_to_mcleodganj-back.webp",
    "frontPrint": "Walk_to_mcleodganj-front.png",
    "backPrint": "Walk_to_mcleodganj-back.png",
    "date": "29052026",
    "distance": "3.8 km",
    "duration": "2 h 10 min",
    "pauses": 9
  },
  {
    "name": "Walk to naddi",
    "file": "Walk_to_naddi",
    "caption": "Offgrid in naddi",
    "location": "Dharamsala, India",
    "front": "Walk_to_naddi-front.webp",
    "back": "Walk_to_naddi-back.webp",
    "frontPrint": "Walk_to_naddi-front.png",
    "backPrint": "Walk_to_naddi-back.png",
    "date": "30052026",
    "distance": "10.7 km",
    "duration": "7 h 07 min",
    "pauses": 57
  },
  {
    "name": "Walk to st johns",
    "file": "Walk_to_st_johns",
    "caption": "Underwhelming visit to st. johns",
    "location": "Dharamsala, India",
    "front": "Walk_to_st_johns-front.webp",
    "back": "Walk_to_st_johns-back.webp",
    "frontPrint": "Walk_to_st_johns-front.png",
    "backPrint": "Walk_to_st_johns-back.png",
    "date": "31052026",
    "distance": "6.8 km",
    "duration": "3 h 23 min",
    "pauses": 7
  },
  {
    "name": "Walk to Monday market",
    "file": "Walk_to_Monday_market",
    "caption": "Walk to Monday market",
    "location": "Delhi, India",
    "front": "Walk_to_Monday_market-front.webp",
    "back": "Walk_to_Monday_market-back.webp",
    "frontPrint": "Walk_to_Monday_market-front.png",
    "backPrint": "Walk_to_Monday_market-back.png",
    "date": "01062026",
    "distance": "1.5 km",
    "duration": "1 h 39 min",
    "pauses": 11
  },
  {
    "name": "Walk in da park",
    "file": "Walk_in_da_park",
    "caption": "Trying open gym equipement in C9",
    "location": "Delhi, India",
    "front": "Walk_in_da_park-front.webp",
    "back": "Walk_in_da_park-back.webp",
    "frontPrint": "Walk_in_da_park-front.png",
    "backPrint": "Walk_in_da_park-back.png",
    "date": "06062026",
    "distance": "1.8 km",
    "duration": "1 h 18 min",
    "pauses": 15
  },
  {
    "name": "Walking with a dog",
    "file": "Walking_with_a_dog",
    "caption": "Walking with a dog",
    "location": "Greatest Noida, India",
    "front": "Walking_with_a_dog-front.webp",
    "back": "Walking_with_a_dog-back.webp",
    "frontPrint": "Walking_with_a_dog-front.png",
    "backPrint": "Walking_with_a_dog-back.png",
    "date": "12062026",
    "distance": "642 m",
    "duration": "17 min",
    "pauses": 3
  },
  {
    "name": "Dog walked me",
    "file": "Dog_walked_me",
    "caption": "Dog walked me",
    "location": "Greatest Noida, India",
    "front": "Dog_walked_me-front.webp",
    "back": "Dog_walked_me-back.webp",
    "frontPrint": "Dog_walked_me-front.png",
    "backPrint": "Dog_walked_me-back.png",
    "date": "14062026",
    "distance": "1.7 km",
    "duration": "40 min",
    "pauses": 7
  },
  {
    "name": "Beautiful walk to work because it was raining",
    "file": "Beautiful_walk_to_work_because_it_was_raining",
    "caption": "Beautiful walk to work because it was raining",
    "location": "Delhi, India",
    "front": "Beautiful_walk_to_work_because_it_was_raining-front.webp",
    "back": "Beautiful_walk_to_work_because_it_was_raining-back.webp",
    "frontPrint": "Beautiful_walk_to_work_because_it_was_raining-front.png",
    "backPrint": "Beautiful_walk_to_work_because_it_was_raining-back.png",
    "date": "16062026",
    "distance": "1.0 km",
    "duration": "23 min",
    "pauses": 2
  },
  {
    "name": "Birdwatching and biodiversity parking",
    "file": "Birdwatching_and_biodiversity_parking",
    "caption": "Birdwatching and biodiversity parking",
    "location": "Delhi, India",
    "front": "Birdwatching_and_biodiversity_parking-front.webp",
    "back": "Birdwatching_and_biodiversity_parking-back.webp",
    "frontPrint": "Birdwatching_and_biodiversity_parking-front.png",
    "backPrint": "Birdwatching_and_biodiversity_parking-back.png",
    "date": "18062026",
    "distance": "681 m",
    "duration": "27 min",
    "pauses": 7
  },
  {
    "name": "Dosa run",
    "file": "Dosa_run",
    "caption": "Dosa run",
    "location": "Bengaluru, India",
    "front": "Dosa_run-front.webp",
    "back": "Dosa_run-back.webp",
    "frontPrint": "Dosa_run-front.png",
    "backPrint": "Dosa_run-back.png",
    "date": "06072026",
    "distance": "1.1 km",
    "duration": "1 h 24 min",
    "pauses": 2
  },
  {
    "name": "Kempagowda Security check-in and sprinting to see monisha",
    "file": "Kempagowda_Security_check-in_and_sprinting_to_see_monisha",
    "caption": "Pulling a rom-com sprint at the airport",
    "location": "Bengaluru, India",
    "front": "Kempagowda_Security_check-in_and_sprinting_to_see_monisha-front.webp",
    "back": "Kempagowda_Security_check-in_and_sprinting_to_see_monisha-back.webp",
    "frontPrint": "Kempagowda_Security_check-in_and_sprinting_to_see_monisha-front.png",
    "backPrint": "Kempagowda_Security_check-in_and_sprinting_to_see_monisha-back.png",
    "date": "06072026",
    "distance": "1.2 km",
    "duration": "33 min",
    "pauses": 9
  }
];
window.UPDATED = "23 September 2026";
